RestClients:
  stammdaten:
    UUID: 7ad8fe9b-78d5-49ad-af70-e4b5daa4d239
    Url: https://{host}
    Features:
    - ch.ivyteam.ivy.rest.client.mapper.JsonFeature
    Properties:
      PATH.host: ${ivy.var.stammdaten-connector.host}
