RestClients:
  #This OData service is located at https://graph.microsoft.com/v1.0
  Microsoft 365 (Partial Graph API):
    UUID: 007036dc-72d1-429f-88a7-ba5d5cf5ae58
    Url: http://{ivy.engine.host}:{ivy.engine.http.port}/{ivy.request.application}/api/graphMock
    Icon: res:/webContent/icons/microsoft.png
    Features:
    - ch.ivyteam.ivy.rest.client.mapper.JsonFeature
    - ch.ivyteam.ivy.rest.client.security.CsrfHeaderFeature
    Properties:
      AUTH.appId: notmyid
      AUTH.secretKey: ${decrypt:\u0054\u001D\u007D\u00A0\u0018\u00F5\u00B4\u00C9\u0073\u00E4\u0012\u0089\u00BC\u008F\u00B1\u00C6\u00DA\u00C9\u00CA\u000D\u004C\u002F\u00B5\u00E3\u00B0\u00D2\u00E3\u00BF\u005C\u0065\u0032\u00F5\u0082\u0005\u0028\u00EA\u0012\u00B1\u0076\u0052\u006B\u00EA\u005F\u00CE\u00A1\u00E0\u00CA\u004D\u0047\u0065\u0043\u004F\u00F4\u00DE\u0091\u003C\u0035\u0018\u005F\u00F2\u0066\u0026\u00F7\u0002\u00CE\u000E\u00B9\u00FF\u000B\u00FD\u00C3\u00AA\u000E\u0056\u004B\u00F8\u00AE\u00C9\u00E1\u0068}
      AUTH.scope: user.read calendars.read
      AUTH.baseUri: http://{ivy.engine.host}:{ivy.engine.http.port}/{ivy.request.application}/api/graphAuthMock
      jersey.client.connectorProvider: org.glassfish.jersey.client.HttpUrlConnectorProvider
