Variables:

  sharepoint-connector:
    permissions: "https://graph.microsoft.com/.default"

  planer-connector:
    permissions: "https://graph.microsoft.com/.default"

  microsoft-connector:

    # Your Azure Application (client) ID
    appId: ""

    # Secret key from your applications "certificates & secrets"
    # [password]
    secretKey: ""
    
    # work with app permissions rather than in delegate of a user
    # set to 'true' if no user consent should be accuired and adjust the 'tenantId' below.
    useAppPermissions: false
    
    # tenant to use for OAUTH2 request.
    # the default 'common' fits for user delegate requests.
    # set the Azure Directory (tenant) ID, for application requests.
    tenantId: "common"

    # permissions to request access to.
    # you may exclude or add some, as your azure administrator allows or restricts them.
    # for sharepoint-demos, the following must be added: Sites.Read.All Files.ReadWrite
    permissions: "user.read Calendars.ReadWrite mail.readWrite mail.send Tasks.ReadWrite Chat.Read offline_access"
    
    teams-notification:
      #permissions: "https://graph.microsoft.com/.default"
      permissions: "Chat.ReadWrite"
      tenantId: "common"
      user: ""
      # [password]
      password: ""
      