name: CI-Build

on: 
  push:
  workflow_call:
    inputs:
      mvnArgs:
        type: string
        required: false
    secrets:
      mvnArgs:
        required: false

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin

    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v20
      env:
        WUSER: ${{ secrets.WALO_USER }}
        WPASS: ${{ secrets.WALO_PASS }}
      with:
        servers: >
          [
            {
              "id": "walo.engine",
              "username": "${env.WUSER}",
              "password": "${env.WPASS}",
              "configuration": {
                "httpConfiguration": {
                  "all": {
                    "usePreemptive": "true"
                  }
                }
              }
            }
          ]

    - name: Build with Maven
      env:
        WUSER: ${{ secrets.WALO_USER }}
        WPASS: ${{ secrets.WALO_PASS }}
      run: mvn clean verify --batch-mode ${{ inputs.mvnArgs }} ${{ secrets.mvnArgs }}

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        junit_files: |
          */target/*-reports/*.xml
          !*/target/*-reports/failsafe-summary.xml

    - name: Archive build artifact
      uses: actions/upload-artifact@v3
      with:
        path: |
          */target/*.iar
          *-app/target/*.zip

